"""empty message

Revision ID: 58d788170006
Revises: b8f2f36ecd38
Create Date: 2017-02-05 21:50:06.338687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d788170006'
down_revision = 'b8f2f36ecd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_first_name', table_name='employees')
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.drop_index('ix_employees_last_name', table_name='employees')
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.create_index('ix_employees_last_name', 'employees', ['last_name'], unique=True)
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.create_index('ix_employees_first_name', 'employees', ['first_name'], unique=True)
    # ### end Alembic commands ###
