"""empty message

Revision ID: b8f2f36ecd38
Revises: 0f15762d2a05
Create Date: 2017-02-05 21:45:54.946585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8f2f36ecd38'
down_revision = '0f15762d2a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('employees', 'emp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('employees', 'id')
    # ### end Alembic commands ###
